version: '2'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - influxdb-volume:/var/lib/influxdb
    ports:
      - "8086:8086" 
      - "8089:8089"
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    restart: always
    volumes:
      - grafana-volume:/var/lib/grafana
  mqtt:  
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /home/hub/config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - default
  node-red:
    build: node-red
    volumes:
       - node-red-volume:/data
    ports:
       - "1880:1880"
    depends_on:
        - mqtt
    restart: always
    environment:
      # default credentials: admin:password
      # generate password: https://nodered.org/docs/security#generating-the-password-hash 
      # escape $ with by $$
      - USERNAME=admin
      - PASSWORD=$$2a$$08$$zZWtXTja0fB1pzD4sHCMyOCMYz2Z6dNbM6tl8sJogENOMcxWV9DN. 
networks:
  hubinternal:
volumes:
  node-red-volume:
    external: true
  influxdb-volume:
    external: true
  grafana-volume:
    external: true
